apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: api-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-test
  template:
    metadata:
      labels:
        app: api-test
    spec:
      containers:
      - name: api-test
        image: 913891584254.dkr.ecr.sa-east-1.amazonaws.com/test-actions:latest
        ports:
        - containerPort: 8080