apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-actions-deployment
  labels:
    app: test-actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-actions
  template:
    metadata:
      labels:
        app: test-actions
    spec:
      containers:
      - name: test-actions
        image: 913891584254.dkr.ecr.sa-east-1.amazonaws.com/test-actions:d57e304d0e10484637fabc0fe17368f23d7e44b5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080