apiVersion: v1
kind: Service
metadata:
  name: test-actions-service
spec:
  selector:
    app.kubernetes.io/name: test-actions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
